<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\PersonalBrand.Infrastructure\PersonalBrand.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e7f75088-d639-4b03-8653-2302928aa0e8</UserSecretsId>
  </PropertyGroup>

</Project>
